"""update review

Revision ID: 358ec0916a5b
Revises: 7e560a774ded
Create Date: 2024-10-02 16:09:46.910311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358ec0916a5b'
down_revision = '7e560a774ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
